#!/bin/bash

COMMIT_REGEX="\[(.*)\-(.*)\]\[(.*)\] (chore|feat|fix|refactor|style|test|docs): [A-Z].*"

COMMIT_MSG=$(head -n 1 "$1")

if ! [[ "$COMMIT_MSG" =~ $COMMIT_REGEX ]]; then
    echo "ERROR: Commit message format is invalid."
    echo "Format should be: [RONIN-102][Fuji] feat: Implement addUser()"
    exit 1
fi

exit 0
