spring:
  config:
    import:
      optional:file:./local/.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: ${APPLICATION_NAME}
